freeze_base_model: True
init_sigmoid_head: "lm_head"  # "lm_head" or path to a sigmoid checkpoint
negative_sampling: True
negative_sampling_ratio: 10
negative_sampling_method: "token_freq,softmax_probs"  # comma separated if want to combine multiple ones
combine_neg_distribution: "independent"
negative_sampling_avoid_dominant: True
temperature_neg_sampling_softmax: 2
weight_positive: "None"  # "None" "balance"
find_dominant_kwargs:
  cut_point_mode: "first"
  find_dominant_method: "difference_jump"
  p_jump: 0.3
  epsilon: 0.005